<a href="https://colab.research.google.com/github/codyub/ESAA_0905-Mon-_1/blob/main/100_Numpy_exercises(1-25).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [120]:
np.version
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [12]:
a.size

10

#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [121]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 6. Create a vector with values ranging from 10 to 49 (★☆☆)

In [122]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 7. Reverse a vector (first element becomes last) (★☆☆)

In [123]:
np.flip(a)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [125]:
a = np.arange(0,9)
print(a)
a.reshape((3, 3))

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 9. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [126]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a)

(array([0, 1, 4]),)

#### 10. Create a 3x3 identity matrix (★☆☆)
Hint : identity & eye, try to use 'help' to learn how to use two functions of numpy

In [127]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 11. Create a 3x3x3 array with random values (★☆☆)
Hint : numpy.random.random

In [128]:
np.random.random((3,3,3))

array([[[0.02861077, 0.47944261, 0.02261409],
        [0.423789  , 0.57292848, 0.98215154],
        [0.68153927, 0.69819943, 0.1615809 ]],

       [[0.77421803, 0.56828871, 0.74741715],
        [0.32544063, 0.16123389, 0.09784833],
        [0.6187725 , 0.40132516, 0.3912104 ]],

       [[0.39537068, 0.58069998, 0.85004119],
        [0.9780369 , 0.50044588, 0.9625256 ],
        [0.91943208, 0.71048009, 0.34729991]]])

#### 12. Create a 10x10 array with random values and find the **min**imum and **max**imum values (★☆☆)

In [129]:
a = np.random.random((10,10))
print(a)
print(np.max(a))
print(np.min(a))

[[6.92973969e-01 9.16556868e-01 7.00017273e-01 1.42094425e-01
  2.96898457e-01 4.77318407e-01 4.80044052e-01 8.39390260e-01
  9.70279244e-01 5.17346392e-01]
 [7.78864593e-01 9.95768052e-01 6.73879170e-01 8.30247285e-01
  2.37047496e-01 1.27573371e-01 4.69493215e-01 7.71295494e-01
  9.57694796e-01 1.10792779e-01]
 [9.86937415e-01 6.64935170e-01 9.05686731e-02 4.32876674e-01
  8.56310035e-01 1.39133924e-01 4.77534419e-01 8.36637681e-01
  2.18100322e-01 3.72011582e-01]
 [8.17879153e-01 5.17420667e-01 4.26576794e-01 1.31585545e-01
  4.94171865e-01 3.29620588e-01 6.54434855e-01 6.41960090e-01
  8.18220865e-01 7.51658971e-01]
 [9.23912614e-01 8.94140501e-01 7.23540378e-01 2.29046651e-01
  7.57390317e-01 1.97075941e-01 8.13168658e-01 7.76711591e-01
  1.90666559e-01 9.64123937e-01]
 [3.55200930e-01 8.94848092e-01 9.11535315e-01 5.89126096e-01
  2.86127812e-01 8.23143371e-01 3.30789474e-01 4.69339477e-01
  8.88156516e-01 1.45113495e-01]
 [3.94428135e-01 6.66255138e-01 1.38010820e-01 9.46897715e

#### 13. Create a random vector of size 30 and find the **mean** value (★☆☆)

In [130]:
a = np.random.random((30))
print(a)
print(np.mean(a))

[0.0330933  0.9259149  0.8526617  0.56702227 0.98801504 0.32132256
 0.0246717  0.84429402 0.46818441 0.84102275 0.11718203 0.85259274
 0.63259105 0.8290563  0.4207756  0.88308723 0.42941338 0.17826324
 0.3875987  0.43584108 0.93198875 0.77322261 0.43154447 0.20819638
 0.1038113  0.5823333  0.18856721 0.7581312  0.06704336 0.30784699]
0.5128429854433966


#### 14. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [131]:
x = np.ones((5,5))
print(x)

x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 15. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [38]:
0 * np.nan # nan

nan

In [39]:
np.nan == np.nan # False

False

In [40]:
np.inf > np.nan # False

False

In [41]:
np.nan - np.nan # nan

nan

In [42]:
np.nan in set([np.nan]) # True

True

In [43]:
0.3 == 3 * 0.1 # False

False

#### 16. Create a 5x5 matrix with values 1,2,3,4 just below the **diag**onal (★☆☆)

In [45]:
a = np.diag([1, 2, 3, 4, 5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

#### 17. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [132]:
a = np.zeros((8,8))
a[1::2,::2] = 1 
a[::2,1::2] = 1
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 18. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)
Hint : use 'numpy.unravel_index(value, (x, y, z))

In [133]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 19. Normalize a 5x5 random matrix (★☆☆)
Hint : $Z = \frac{X - \overline{X}}{S}$

In [134]:
x= np.random.random((5,5))
z = (x - np.mean(x)) / np.std(x)
z

array([[-1.31560147, -0.83067775,  1.50539405,  0.94871822, -0.61484515],
       [-1.25090146,  1.06480312, -1.76250294,  0.3037372 , -1.03828239],
       [-0.85041305,  0.12110195, -0.66951573,  0.94055606,  1.51416623],
       [ 0.6866965 , -1.73258963,  0.49278599,  1.48465196,  0.60525132],
       [-0.22583399,  0.23201169,  1.03318504, -0.44551323, -0.19638256]])

#### 20. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)
Hint : modify the code below
```python
numpy.dtype([(value, numpy.ubyte), … , (value, numpy.ubyte)])
```

In [135]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 21. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [53]:
a = np.random.random((5,3))
b = np.random.random((3,2))

a@b

array([[0.26440837, 0.31568109],
       [0.84806063, 1.52318697],
       [0.26424114, 0.65600107],
       [0.83836049, 1.65830097],
       [0.87802085, 1.25977428]])

#### 22. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [137]:
a = np.arange(11)
print(a)
a[(3 <= a) & (a<= 8)] *= -1 
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 23. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [58]:
print(sum(range(5),-1)) # 9

9


In [138]:
from numpy import *
print(sum(range(5),-1)) # 10

10


#### 24. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [140]:
Z = np.random.randint(0,10,10)
Z

array([9, 1, 1, 3, 7, 7, 3, 7, 2, 0])

In [141]:
Z**Z

array([387420489,         1,         1,        27,    823543,    823543,
              27,    823543,         4,         1])

In [142]:
2 << Z >> 2 

array([256,   1,   1,   4,  64,  64,   4,  64,   2,   0])

In [143]:
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False])

In [144]:
1j*Z

array([0.+9.j, 0.+1.j, 0.+1.j, 0.+3.j, 0.+7.j, 0.+7.j, 0.+3.j, 0.+7.j,
       0.+2.j, 0.+0.j])

In [145]:
Z/1/1

array([9., 1., 1., 3., 7., 7., 3., 7., 2., 0.])

In [146]:
Z<Z>Z # 이건 틀림

ValueError: ignored

#### 25. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [67]:
np.array(0) / np.array(0) # nan

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [68]:
np.array(0) // np.array(0) # 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [72]:
np.array([np.nan]).astype(int).astype(float) # array([-9.22337204e+18]) (float 형태로 나옴)

array([-9.22337204e+18])