<a href="https://colab.research.google.com/github/codyub/ESAA_0905-Mon-_1/blob/main/100_Numpy_exercises(26~39).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 26. How to find common values between two arrays? (★☆☆)
```python
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
```
Hint : use `numpy.random.randint(start, end, size)`

In [4]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)

In [5]:
np.intersect1d(Z1,Z2)

array([4, 6, 9])

#### 27. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [6]:
np.sqrt(-1) == np.emath.sqrt(-1) # False

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

In [7]:
np.sqrt(-1) # nan

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


nan

In [8]:
np.emath.sqrt(-1) # 1j

1j

#### 28. How to get all the dates corresponding to the month of July 2016? (★★☆)
Hint : modify the code below
```python
Z = np.arange('start', 'end', dtype='datetime64[D]')
```

In [9]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 29. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)
Hint : use `numpy.add`, `numpy.divide`,`numpy.negative`, `numpy.multiply` and parameter `out` of the funtions

In [10]:
A = np.eye(3)
B = np.random.random((3,3))

# 이건 왜 안되는걸까?
print((A+B)@(A*(-1/2)))

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

[[-0.50762633 -0.04409168 -0.33758368]
 [-0.36465402 -0.91334062 -0.43235133]
 [-0.01012562 -0.05214146 -0.89954753]]


array([[-0.50762633, -0.        , -0.        ],
       [-0.        , -0.91334062, -0.        ],
       [-0.        , -0.        , -0.89954753]])

#### 30. Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)
Hint : `%`, `//`

In [11]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[4.67066236 5.6389192  7.22504763 3.90266294 7.55403802 5.17748632
 2.55136193 2.44803922 1.27215386 1.43897653]
[4. 5. 7. 3. 7. 5. 2. 2. 1. 1.]
[4. 5. 7. 3. 7. 5. 2. 2. 1. 1.]
[4. 5. 7. 3. 7. 5. 2. 2. 1. 1.]
[4 5 7 3 7 5 2 2 1 1]
[4. 5. 7. 3. 7. 5. 2. 2. 1. 1.]


#### 31. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [12]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 32. Create a random vector of size 10 and sort it (★★☆)

In [13]:
a = np.random.randint(0,10,10)
print(a)
np.sort(a)

[7 8 1 2 4 1 6 9 2 9]


array([1, 1, 2, 2, 4, 6, 7, 8, 9, 9])

#### 33. Consider two random array A and B, check if they are equal (★★☆)
```python
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
```
Hint : Use `numpy.array_equal()`

In [14]:
np.array_equal(A,B)

False

#### 34. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Hint 1 : Note that cartesian coodinate **(x, y)** can be represented as  polar coordinates **(distance from origin to (x,y), angle from the x-axis)**

Hint 2 : Use `numpy.sqrt` and `numpy.arctan2`

In [15]:
z = np.random.random((10, 2))
x, y = z[:,0],z[:,1] #x와 y에 각각 0열, 1열 할당
r = np.sqrt(x**2+y**2) # 데카르트 좌표
p = np.arctan2(y,x) # 극좌표
print(r)
print(p)

[0.55453386 0.76497959 0.50501163 0.75560856 0.80018087 0.85408964
 0.614132   1.03389115 1.06277363 0.63703929]
[1.40207594 0.42108021 1.02617793 0.41672002 1.25342003 1.30886929
 0.51740025 1.19149574 0.87854138 0.80022366]


#### 35. Create random vector Z of size 10 and replace the maximum value by 0 (★★☆)
Hint : We can see the index of maximum value using `Z.argmax()`

In [30]:
# 방법1
z = np.random.random(10)
print(z)
z[z==np.max(z)]=0
print(z)

[0.70093778 0.46073156 0.48318889 0.82654102 0.16205321 0.7746331
 0.42878499 0.81267632 0.0697744  0.00111655]
[0.70093778 0.46073156 0.48318889 0.         0.16205321 0.7746331
 0.42878499 0.81267632 0.0697744  0.00111655]


In [29]:
# 방법2
z = np.random.random(10)
z[z.argmax()] = 0
z

array([0.4229988 , 0.4012926 , 0.48023029, 0.25158619, 0.24325548,
       0.26514315, 0.33719411, 0.19068195, 0.        , 0.34782439])

#### 36. How to find the closest value (to a given scalar v) in a vector Z? (★★☆)
```python
Z = np.arange(100)
v = np.random.uniform(0,100)
```
Hint : Coumpute the distances between the each elements of Z and the scalar v. After that, we can see the index of minimum value using `argmin()`.  

In [40]:
Z = np.arange(100)
v = np.random.uniform(0,100) # float 이므로 그 값 자체로 for문을 돌릴 수는 없다. 


# 주어진 값에서 가장 가까운 값 찾기
print(np.abs((Z-v)))
i = np.abs((Z-v)).argmin()
# 가장 가까운값의 인덱스와 그 값 출력
print('인덱스:', i ,'/값:', Z[i])

[57.11858462 56.11858462 55.11858462 54.11858462 53.11858462 52.11858462
 51.11858462 50.11858462 49.11858462 48.11858462 47.11858462 46.11858462
 45.11858462 44.11858462 43.11858462 42.11858462 41.11858462 40.11858462
 39.11858462 38.11858462 37.11858462 36.11858462 35.11858462 34.11858462
 33.11858462 32.11858462 31.11858462 30.11858462 29.11858462 28.11858462
 27.11858462 26.11858462 25.11858462 24.11858462 23.11858462 22.11858462
 21.11858462 20.11858462 19.11858462 18.11858462 17.11858462 16.11858462
 15.11858462 14.11858462 13.11858462 12.11858462 11.11858462 10.11858462
  9.11858462  8.11858462  7.11858462  6.11858462  5.11858462  4.11858462
  3.11858462  2.11858462  1.11858462  0.11858462  0.88141538  1.88141538
  2.88141538  3.88141538  4.88141538  5.88141538  6.88141538  7.88141538
  8.88141538  9.88141538 10.88141538 11.88141538 12.88141538 13.88141538
 14.88141538 15.88141538 16.88141538 17.88141538 18.88141538 19.88141538
 20.88141538 21.88141538 22.88141538 23.88141538 24

#### 37. What is the equivalent of enumerate for numpy arrays? (★★☆)
Hint : Use `numpy.ndenumerate()`or `numpy.ndindex()`

Example of the output :
```python
Z = np.arange(9).reshape(3,3)
```
```python
# output
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
```

In [41]:
# Enumerate: 순서목록? 다차원 배열에서의 각 원소에 대한 인덱스 출력
Z = np.arange(9).reshape(3,3)
print(Z)
for index, value in np.ndenumerate(Z):
    print(index, value)

print(Z)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 38. How to randomly place p elements in a 2D array? (★★☆)
Hint : modify the code below
```python
n = 'size of a 2D array'
p = 'the number of elements that you want to place'
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace = False),'value that you want to place')
print(Z)
```

In [43]:
n = 5
p = 3
Z = np.zeros((5,5))
np.put(Z, np.random.choice(range(n*n), p, replace = False),4)
print(Z)

[[0. 0. 4. 0. 4.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [4. 0. 0. 0. 0.]]


#### 39. How to sort an array below by the nth column? (★★☆)
```python
Z = np.random.randint(0,10,(3,3))
```

In [46]:
z = np.random.randint(0,10,(3,3))

In [47]:
# column 1
print(z[z[:,0].argsort()])

[[1 2 8]
 [2 4 2]
 [6 5 1]]


In [48]:
# column 2
print(z[z[:,1].argsort()])

[[1 2 8]
 [2 4 2]
 [6 5 1]]


In [49]:
# column 3
print(z[z[:,2].argsort()])

[[6 5 1]
 [2 4 2]
 [1 2 8]]
