<a href="https://colab.research.google.com/github/codyub/ESAA/blob/main/%EB%AA%A8%EB%8D%B8%ED%9B%88%EB%A0%A8_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **| 모델 훈련 연습 문제**
___
- 출처 : 핸즈온 머신러닝 Ch04 연습문제 1, 5, 9, 10
- 개념 문제의 경우 텍스트 셀을 추가하여 정답을 적어주세요.

### **1. 수백만 개의 특성을 가진 훈련 세트에서는 어떤 선형 회귀 알고리즘을 사용할 수 있을까요?**
___


- 확률적 경사 하강법, 미니배치 경사 하강법
- 훈련 세트가 맞으면 배치 경사 하강법도 가능 (-> 가능하지만 느릴듯?)
- 정규 방정식, SVD을 활용할 수는 없다(계산 복잡도가 너무 올라감)

### **2. 배치 경사 하강법을 사용하고 에포크마다 검증 오차를 그래프로 나타내봤습니다. 검증 오차가 일정하게 상승되고 있다면 어떤 일이 일어나고 있는 걸까요? 이 문제를 어떻게 해결할 수 있나요?**
___

- 학습률이 너무 높아서 알고리즘이 발산하는 것일 수 있다.
- 훈련 에러도 상승하고 있다면 이러한 경향이 확실하므로 학습률을 낮춰야 한다. 
- 하지만 훈련 에러는 상승하고 있지 않다면, 모델이 훈련 세트에 과대 적합 되고 있는 것이므로 훈련을 멈춰야 한다. 

### **3. 릿지 회귀를 사용했을 때 훈련 오차가 검증 오차가 거의 비슷하고 둘 다 높았습니다. 이 모델에는 높은 편향이 문제인가요, 아니면 높은 분산이 문제인가요? 규제 하이퍼파라미터 $\alpha$를 증가시켜야 할까요 아니면 줄여야 할까요?**
___

- 둘다 거의 비슷하게 높다면 과소 적합되었을 것이므로 편향이 높다는 것을 의미한다. 
- 즉, 규제 하이퍼 파라미터를 감소시켜야 한다.

### **4. 다음과 같이 사용해야 하는 이유는?**
___
- 평범한 선형 회귀(즉, 아무런 규제가 없는 모델) 대신 릿지 회귀
- 릿지 회귀 대신 라쏘 회귀
- 라쏘 회귀 대신 엘라스틱넷 -> 쓰이는 특성이 적을 때 사용하면 좋다

(1) 평범한 선형 회귀 대신 릿지 회귀: 규제가 없는 모델보다 있는 모델이 일반적으로 성능이 더 좋음

(2) 라쏘 회귀는 가중치를 0으로 만들어 중요하지 않은 변수를 제거하는 feature selection 역할을 해줄 수 있다. 따라서, 단지 몇 개의 특성만이 유용할 것이라 의심될 때 사용하면 좋다. 

(3) 라쏘 대신 엘라스틱넷: 몇 개의 특성이 강하게 연관되어 있거나 훈련 샘플보다 특성이 더 많을 때, 라쏘는 불규칙하게 행동하므로, 일반적으로 엘라스틱넷이 더 선호된다. 하지만 추가 파라미터가 생긴다는 문제점이 있을 수 있다.  

### **5. 조기 종료를 사용한 배치 경사 하강법으로 소프트맥스 회귀를 구현해보세요(사이킷런은 사용하지 마세요)**


---



In [ ]:
from sklearn import datasets
iris=datasets.load_iris()

In [ ]:
X = iris['data'][:,(2,3)]
y = iris['target']

In [ ]:
import numpy as np
# 모든 샘플에 편향 추가
X_with_bias = np.c_[np.ones([len(X),1]), X] # 컬럼 처럼 이어 붙이기(수직)
np.random.seed(2042)

X_with_bias

array([[1. , 1.4, 0.2],
       [1. , 1.4, 0.2],
       [1. , 1.3, 0.2],
       [1. , 1.5, 0.2],
       [1. , 1.4, 0.2],
       [1. , 1.7, 0.4],
       [1. , 1.4, 0.3],
       [1. , 1.5, 0.2],
       [1. , 1.4, 0.2],
       [1. , 1.5, 0.1],
       [1. , 1.5, 0.2],
       [1. , 1.6, 0.2],
       [1. , 1.4, 0.1],
       [1. , 1.1, 0.1],
       [1. , 1.2, 0.2],
       [1. , 1.5, 0.4],
       [1. , 1.3, 0.4],
       [1. , 1.4, 0.3],
       [1. , 1.7, 0.3],
       [1. , 1.5, 0.3],
       [1. , 1.7, 0.2],
       [1. , 1.5, 0.4],
       [1. , 1. , 0.2],
       [1. , 1.7, 0.5],
       [1. , 1.9, 0.2],
       [1. , 1.6, 0.2],
       [1. , 1.6, 0.4],
       [1. , 1.5, 0.2],
       [1. , 1.4, 0.2],
       [1. , 1.6, 0.2],
       [1. , 1.6, 0.2],
       [1. , 1.5, 0.4],
       [1. , 1.5, 0.1],
       [1. , 1.4, 0.2],
       [1. , 1.5, 0.2],
       [1. , 1.2, 0.2],
       [1. , 1.3, 0.2],
       [1. , 1.4, 0.1],
       [1. , 1.3, 0.2],
       [1. , 1.5, 0.2],
       [1. , 1.3, 0.3],
       [1. , 1.3

# 데이터 셋을 훈련/검증/테스트 set으로 나누기

In [ ]:
test_ratio = 0.2
validation_ratio = 0.2
total_size = len(X_with_bias)

test_size = int(total_size*test_ratio)
validation_size = int(total_size*validation_ratio)
train_size = total_size - test_size - validation_size

In [ ]:
# 무작위로 순서를 바꿔줌: 섞어줌
rnd_indices = np.random.permutation(total_size)

In [ ]:
# train_size 만큼 분할
X_train = X_with_bias[rnd_indices[:train_size]]
y_train = y[rnd_indices[:train_size]]

In [ ]:
# valid와 tset 세트도 나눠줌
X_valid = X_with_bias[rnd_indices[train_size:-test_size]]
y_valid = y[rnd_indices[train_size:-test_size]]
X_test = X_with_bias[rnd_indices[-test_size:]]
y_test = y[rnd_indices[-test_size:]]

- 타깃은  클래스 인덳 0,1,2 세 개의 종이지만, 소프트 맥스 회귀 모델을 훈련시키기 위해 필요한 것은 타깃의 확률
- 각 샘플에서 확률이 1인 타깃 클래스를 제외한 다른 클래스의 확률은 0으로 만들어주는 원-핫 벡터를 행함
- max=2, 클래스 개수는 3개이므로, +1을 해 n_classes=3
- 

In [ ]:
def to_one_hot(y):
  n_classes = y.max() + 1
  m = len(y)
  Y_one_hot = np.zeros((m,n_classes))
  Y_one_hot[np.arange(m),y] = 1
  return Y_one_hot

# 원-핫 연습

In [ ]:
y_train[:10]

array([1, 0, 0, 1, 0, 2, 1, 0, 0, 0])

In [ ]:
to_one_hot(y_train[:10])

array([[0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [ ]:
Y_train_one_hot = to_one_hot(y_train)
Y_valid_one_hot = to_one_hot(y_valid)
Y_test_ont_hot = to_one_hot(y_test)

# 소프트맥스 함수 만들기
- 클래스 k에 들어갈 추정 확률

In [ ]:
def softmax(logits):
  exps = np.exp(logits)
  exp_sums = np.sum(exps, axis=1, keepdims=True)
  return exps/exp_sums

# 입력과 출력의 개수 정의

In [ ]:
n_inputs = X_train.shape[1]
n_outputs = len(np.unique(y_train))

https://analysis-flood.tistory.com/91 : 참고