<a href="https://colab.research.google.com/github/codyub/ESAA_0905-Mon-_1/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_%EC%99%84%EB%B2%BD_%EA%B0%80%EC%9D%B4%EB%93%9C(1_38p).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

파이썬 기반의 머신러닝과 생태계 이해

# **1.	머신러닝의 개념**
일반적으로 애플리케이션을 수정하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법을 통칭. 머신러닝 알고리즘은 데이터를 기반으로 통계적인 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내의 패턴을 스스로 인지하고 신뢰도 있는 예측 결과를 도출한다. 


# **-	머신러닝의 분류**
1)	지도학습: 예) 분류, 회귀, 추천시스템, 시각/음성 감지/인지, 텍스트 분석, NLP

2)	비지도학습: 예) 클러스터링, 차원축소, 강화학습 ->	강화학습은 비지도 학습의 한 종류!

-	데이터 전쟁
머신러닝에서 알고리즘보다는 데이터가 중요하다고 볼 수 있음. = 머신러닝의 단점(데이터에 매우 의존적임) = 좋은 품질의 데이터가 아니면 머신러닝의 수행 결과도 좋지 않다. 
좋은 모델을 위해서는 최적의 알고리즘 모델과 파라미터 구축 능력만이 아닌, 데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적 데이터 기반으로 알고리즘을 구동할 수 있도록 준비해야 함. 

-	파이썬과 R 기반의 머신러닝 비교
R: 통계 전용 프로그램 언어
Python: 개발 전문 프로그램 언어, 딥러닝 프레임 워크인 텐서플로, 케라스, 파이토치 등 지원. 


# **2.	파이썬 머신러닝 생태계를 구성하는 주요 패키지**

- 머신러닝 패키지: 데이터 마이닝 기반(**사이킷런**), 비정형데이터(**텐서플로, 케라스**) 

- 행렬/선형대수/통계 패키지: 머신러닝의 이론적인 백그라운드 역할, **선형대수(넘파이)**, **자연과학과 통계(사이파이)** -> 사이킷런의 기반이 됨

- 데이터 핸들링: 대표적인 데이터 처리 패키지(판다스), 2차원 데이터 처리에 특화됨, **matplotlib **호출로 쉽게 시각화 가능

- 시각화: matplotlib이 대표적 -> 보완: **seaborn(판다스와 쉬운 연동, 함축적인 api, 분석을 위한 다양한 그래프/차트 제공)**

- 주피터 노트북: 대화형 파이썬 툴, 전체 프로그램에서 특정 코드 영역별로 개별 수행 지원, 영역별 코드 이해 명확

-	파이썬 머신러닝을 위한 S/W 설치


# **3.	넘파이(13p)**
Numerical python을 의미하며, 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지. 많은 머신러닝 알고리즘이 넘파이 기반으로 작성됨.


# **-	넘파이 ndarray 개요**

In [ ]:
import numpy as np

In [ ]:
array1 = np.array([1,2,3]) # ndarray 형태로 반환
print("array1 type : ", type(array1))
print("array1 shape : ", array1.shape) # 1차원이므로, (열,) 로 결과가 나옴

array1 type :  <class 'numpy.ndarray'>
array1 shape :  (3,)


In [ ]:
array2 = np.array([[1,2,3],[4,5,6]])
print(array2 )
print("array2 type : ", type(array2))
print("array2 shape : ", array2.shape) # 2차원 이므로, (행, 열) 순서로 shape을 알려줌

[[1 2 3]
 [4 5 6]]
array2 type :  <class 'numpy.ndarray'>
array2 shape :  (2, 3)


In [ ]:
array3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(array3)
print("array3 type : ", type(array3))
print("array3 shape : ", array3.shape) # 3차원 이므로

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
array3 type :  <class 'numpy.ndarray'>
array3 shape :  (2, 2, 3)


# **-	Ndarray의 데이터 타입**

숫자 값, 문자 값, 불 값 등 모두 가능, ndarray내의 데이터 타입은 그 연산의 특성상 같은 데이터 타입만 가능함. Ndarray 내의 데이터 타입은 dtype 속성으로 확인할 수 있음. 

In [ ]:
list1 = [1,2,3,4]
print(type(list1))
array1 = np.array(list1) # list는 쉽게 ndarray 형태로 바꿀 수 있다. 
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4] int64


In [ ]:
list2 = [1,2,3,4, 'aa']
print(type(list2))
array2 = np.array(list2) # 다른 데이터 타입으로 구성된 값을 넣으면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.
print(type(array2))
print(array2, array2.dtype)

<class 'list'>
<class 'numpy.ndarray'>
['1' '2' '3' '4' 'aa'] <U21


In [ ]:
# ndarray 내의 데이터 타입 변경 : astype()
array_int = np.array([1,2,3,4])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int64')
print(array_float, array_int1.dtype)

[1. 2. 3. 4.] float64
[1. 2. 3. 4.] int64



# - ndarray 편리하게 생성하기 **굵은 텍스트**

In [ ]:
# ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우
# ndarray 편리하게 생성하기:1) arange()
s_array = np.arange(2,10) # range() 함수와 비슷한 규칙을 갖고 있다고 생각하면 됨. 초기값을 설정하지 않으면 defalt로 0
print(s_array)
print(s_array.dtype,s_array.shape)

# ndarray 편리하게 생성하기:2) zeros()
z_array = np.zeros((3,2), dtype='int64') # 2차원의 3행 2열인 0으로 이뤄진 행렬을 생성
print(z_array)
print(z_array.dtype,z_array.shape)

# ndarray 편리하게 생성하기:3) ones()
o_array = np.ones((3,2)) # 2차원의 3행 2열인 1로 이뤄진 행렬을 생성
print(o_array)
print(o_array.dtype,o_array.shape)

[2 3 4 5 6 7 8 9]
int64 (8,)
[[0 0]
 [0 0]
 [0 0]]
int64 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


-	Ndarray의 차원과 크기를 변경하는 reshape()

- 지정된 사이즈로 변경이 불가능하면 오류가 발생한다.

In [ ]:
array1 = np.arange(10)
print("array1: \n", array1)

array2 = array1.reshape(2,5)
print("array2: \n", array2)

array3 = array1.reshape(5,2)
print("array3: \n", array3)

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) # 호환될 수 있는 2차원 array로 변환하되, 고정된 5개의 칼럼에 맞는 로우를 자동으로 새롭게 생성해 변환하라 의미
print("array2 shape: ", array2.shape)

array3 = array1.reshape(5, -1)
print("array3 shape: ", array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print("array3d:\n", array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print("array5:\n", array5.tolist())
print("array5 shape: ", array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print("array6:\n", array6.tolist())
print("array6 shape: ", array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:  (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:  (8, 1)


# **-	넘파이의 ndarray의 데이터 세트 선택하기 – 인덱싱**

1)	특정한 데이터만 추출

2)	슬라이싱

3)	팬시 인덱싱: 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환. 

4)	불린 인덱싱: 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True 에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환.

슬라이싱, 팽시 인덱싱, 불린 인섹싱으로 추출한 데이터들은 모두 ndarray 타입

In [ ]:
# 단일 값 추출

# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(1,10)
print('array1: ', array1)

value = array1[2]
print('value : ', value)
print(type(value)) # ndarray 타입이 아닌, ndarray 내의 데이터 값을 의미함. 

array1:  [1 2 3 4 5 6 7 8 9]
value :  3
<class 'numpy.int64'>


In [ ]:
# 데이터 값 수정도 가능
array1[0] = 9
array1[8] = 0
print('array1: ', array1)

array1:  [9 2 3 4 5 6 7 8 0]


In [ ]:
# 다차원 ndarray에서 단일 값 추출
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print("(row=0, col=0) index 가리키는 값: ", array2d[0,0]) # axis0 = row, axis1 = col
print("(row=0, col=1) index 가리키는 값: ", array2d[0,1])
print("(row=1, col=0) index 가리키는 값: ", array2d[1,0])
print("(row=2, col=2) index 가리키는 값: ", array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값:  1
(row=0, col=1) index 가리키는 값:  2
(row=1, col=0) index 가리키는 값:  4
(row=2, col=2) index 가리키는 값:  9


In [ ]:
# 슬라이싱 : 시작 인덱스 ~ 종료인덱스 -1 위치까지 잘라냄
array1 = np.arange(1,10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print("array2d:\n",array2d)

print('array2d[0:2,0:2] \n',array2d[0:2,0:2])
print('array2d[:2,0] \n',array2d[:2,0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2] 
 [[1 2]
 [4 5]]
array2d[:2,0] 
 [1 4]


In [ ]:
print(array2d[0])
print(array2d[1])
print('print(array2d[0]) shape: ', array2d[0].shape, 'print(array2d[1]) shape: ', array2d[1].shape)

[1 2 3]
[4 5 6]
print(array2d[0]) shape:  (3,) print(array2d[1]) shape:  (3,)


In [ ]:
# 팬시 인덱싱
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1],2] # (0,2)와 (1,2)가 나온 것
print("array2d[[0,1],2] -> ", array3.tolist())

array4 = array2d[[0,1],:2] # (0,0:2),(1,0:2)이 나온 것
print("array2d[[0,1],:2] -> ", array4.tolist())

array5 = array2d[[0,1]] #  (0,:), (1,:)이 나온 것
print("array2d[[0,1]] -> ", array5.tolist())

array2d[[0,1],2] ->  [3, 6]
array2d[[0,1],:2] ->  [[1, 2], [4, 5]]
array2d[[0,1]] ->  [[1, 2, 3], [4, 5, 6]]


In [ ]:
# 불린 인덱싱: 조건 필터링과 검색을 동시에 할 수 있음. 
array1d = np.arange(1,10)

array3 = array1d[array1d>5]
print("array1d>5 불린 인덱싱 결과 값 : ", array3)

array1d>5 불린 인덱싱 결과 값 :  [6 7 8 9]


In [ ]:
array1d>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [ ]:
boolen_index = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolen_index]
print(array3)

[6 7 8 9]


# **-	행렬의 정렬 – sort()와 argsort()**

np.sort() : 원 행렬은 유지한 채 원 행렬의 정렬된 행렬을 반환

ndarray.sort() : 원 행렬 자체를 정렬한 형태로 반환하며, 반환 값은 None임

argsort() : 정렬된 행렬의 인덱스를 반환 **굵은 텍스트**

In [ ]:
org_array = np.array([3,1,9,5])
print('원본행렬: ', org_array)

#np.sort()로 정렬
sort_array1 = np.sort(org_array) # 원본 행렬 변경 않고 정렬된 형태로 반환
print('np.sort() 호출 후 반환된 정렬 행렬 : ', sort_array1)
print('np.sort() 호출 후 원본 행렬 : ', org_array)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort() # 원본 행렬 자체를 정리된 값으로 변환
print('org_array,sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array)

# 내림차순 적용 방법
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

원본행렬:  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_array,sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]
[9 5 3 1]


In [ ]:
# 2치원 이상의 경우는, axis 축 값 설정을 통해 열방향 또는 행 방향으로 정렬을 수행할 수 있다.
array2d = np.array([[8,12],[7,1]])

print(array2d)

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('row 방향 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('col 방향 정렬: \n', sort_array2d_axis1)

[[ 8 12]
 [ 7  1]]
row 방향 정렬: 
 [[ 7  1]
 [ 8 12]]
col 방향 정렬: 
 [[ 8 12]
 [ 1  7]]


In [ ]:
# 정렬된 행렬의 인덱스를 반환하기
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices)

# 내림차순 정렬된 행렬의 인덱스 구하기
org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices_desc)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]


# **선형대수 연산 – 행렬 내적과 전치행렬 구하기**

행력 내적(행렬곱): 두 행렬 A와 B의 내적 계산 = np.dot()
(일반적으로 행렬을 곱한다고 했을때 계산하는 값이 결과)

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])
dot_product = np.dot(A,B)
print('행렬 내적 결과: \n', dot_product)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


전치행렬: 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬 = np.transpose()

In [ ]:
A = np.array([[1,2,3],[4,5,6]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬: \n', transpose_mat)

A의 전치 행렬: 
 [[1 4]
 [2 5]
 [3 6]]
